import type { Lang } from "../../i18n/ui";

export interface Competence {
	id: string;
	label: Record<Lang, string>;
	/** Importance for an AI Engineer hiring decision (1 = context, 3 = core). */
	weight: 1 | 2 | 3;
	/** Terms are matched lowercase and without accents, as whole words. A trailing plural "s" is optional. */
	terms: readonly string[];
}

export const competences = [
	{
		id: "agents",
		label: { fr: "systèmes agentiques", en: "agentic systems" },
		weight: 3,
		terms: [
			"agent",
			"agentique",
			"agentic",
			"multi-agent",
			"multiagent",
			"langgraph",
			"orchestration",
			"function calling",
			"tool calling",
			"tool use",
			"appels d'outils",
			"mcp",
			"model context protocol",
			"sorties structurees",
			"structured output",
			"autogen",
			"crewai",
		],
	},
	{
		id: "rag",
		label: { fr: "RAG et recherche documentaire", en: "RAG and retrieval" },
		weight: 3,
		terms: [
			"rag",
			"retrieval",
			"retrieval-augmented",
			"retrieval augmented",
			"recherche augmentee",
			"generation augmentee",
			"recherche documentaire",
			"document search",
			"base vectorielle",
			"bases vectorielles",
			"vector database",
			"vector store",
			"embedding",
			"chromadb",
			"llamaindex",
			"recherche semantique",
			"semantic search",
			"indexation",
			"reranking",
		],
	},
	{
		id: "llm",
		label: { fr: "LLM et IA générative", en: "LLMs and generative AI" },
		weight: 2,
		terms: [
			"llm",
			"large language model",
			"grand modele de langage",
			"grands modeles de langage",
			"modele de langage",
			"modeles de langage",
			"language model",
			"ia generative",
			"generative ai",
			"genai",
			"gpt",
			"mistral",
			"llama",
			"prompt",
			"prompting",
			"fine-tuning",
			"fine tuning",
			"langchain",
		],
	},
	{
		id: "evaluation",
		label: {
			fr: "évaluation et auditabilité",
			en: "evaluation and auditability",
		},
		weight: 3,
		terms: [
			"evaluation",
			"evals",
			"observabilite",
			"observability",
			"monitoring",
			"llmops",
			"tracabilite",
			"traceable",
			"traceability",
			"audit",
			"auditable",
			"auditabilite",
			"auditability",
			"explicabilite",
			"explainability",
			"fiabilite",
			"reliability",
			"guardrail",
			"garde-fou",
			"hallucination",
			"verifications croisees",
			"cross-check",
		],
	},
	{
		id: "production",
		label: { fr: "mise en production", en: "production delivery" },
		weight: 2,
		terms: [
			"production",
			"mise en production",
			"deploiement",
			"deployment",
			"industrialisation",
			"industrialiserez",
			"mlops",
			"ci/cd",
			"docker",
			"kubernetes",
			"api",
			"microservice",
			"scalabilite",
			"scalability",
			"securisation",
			"librairies internes",
			"internal libraries",
			"sdk",
		],
	},
	{
		id: "python",
		label: { fr: "Python", en: "Python" },
		weight: 1,
		terms: ["python", "fastapi", "pydantic", "pandas"],
	},
	{
		id: "ml",
		label: { fr: "machine learning", en: "machine learning" },
		weight: 1,
		terms: [
			"machine learning",
			"apprentissage automatique",
			"deep learning",
			"apprentissage profond",
			"pytorch",
			"tensorflow",
			"scikit-learn",
			"sklearn",
			"modelisation",
			"modeling",
			"statistique",
			"statistical",
			"statistics",
		],
	},
	{
		id: "nlp",
		label: {
			fr: "NLP et extraction d'information",
			en: "NLP and information extraction",
		},
		weight: 2,
		terms: [
			"nlp",
			"traitement du langage",
			"traitement automatique du langage",
			"natural language processing",
			"extraction",
			"extract",
			"information extraction",
			"entites nommees",
			"named entity",
			"non structurees",
			"non structures",
			"unstructured",
			"comptes rendus",
			"classement des pieces",
			"document classification",
		],
	},
	{
		id: "multimodal",
		label: { fr: "multimodal et vision", en: "multimodal and vision" },
		weight: 2,
		terms: [
			"multimodal",
			"multimodale",
			"computer vision",
			"vision par ordinateur",
			"image",
			"ocr",
			"pdf",
			"schemas",
			"diagram",
		],
	},
	{
		id: "health",
		label: { fr: "santé", en: "healthcare" },
		weight: 2,
		terms: [
			"sante",
			"health",
			"healthcare",
			"medical",
			"medicale",
			"medicaux",
			"hopital",
			"hopitaux",
			"hospital",
			"hospitalier",
			"clinique",
			"clinical",
			"patient",
			"chu",
			"medecin",
			"physician",
		],
	},
	{
		id: "insurance",
		label: { fr: "assurance", en: "insurance" },
		weight: 2,
		terms: [
			"assurance",
			"insurance",
			"insurer",
			"insurtech",
			"assureur",
			"sinistre",
			"claim",
			"claims management",
			"indemnisation",
			"indemnification",
			"mutuelle",
			"souscription",
			"underwriting",
			"garanties",
			"coverage",
		],
	},
	{
		id: "industry",
		label: {
			fr: "industrie et bureau d'études",
			en: "industry and engineering",
		},
		weight: 1,
		terms: [
			"automobile",
			"automotive",
			"industrie",
			"industriel",
			"industrielle",
			"industrial",
			"manufacturing",
			"bureau d'etudes",
			"design office",
			"documentation technique",
			"technical documentation",
		],
	},
	{
		id: "local-ai",
		label: { fr: "IA locale et open source", en: "local and open-source AI" },
		weight: 2,
		terms: [
			"confidentialite",
			"confidentiality",
			"privacy",
			"rgpd",
			"gdpr",
			"on-premise",
			"on premise",
			"on-prem",
			"en local",
			"souverainete",
			"souveraine",
			"sovereign",
			"open source",
			"open-source",
			"ollama",
		],
	},
	{
		id: "synthetic",
		label: { fr: "données synthétiques", en: "synthetic data" },
		weight: 2,
		terms: [
			"donnees synthetiques",
			"synthetic data",
			"gan",
			"vae",
			"generation de donnees",
			"data generation",
			"anonymisation",
			"anonymization",
		],
	},
	{
		id: "data",
		label: { fr: "données et bases de données", en: "data and databases" },
		weight: 1,
		terms: [
			"sql",
			"etl",
			"pipeline de donnees",
			"data pipeline",
			"mongodb",
			"neo4j",
			"graph database",
			"base de donnees",
			"database",
			"data engineering",
		],
	},
	{
		id: "cloud",
		label: { fr: "cloud (Azure)", en: "cloud (Azure)" },
		weight: 1,
		terms: ["azure", "cloud", "aws", "gcp"],
	},
	{
		id: "communication",
		label: {
			fr: "accompagnement des métiers",
			en: "working with business teams",
		},
		weight: 1,
		terms: [
			"vulgarisation",
			"acculturation",
			"pedagogie",
			"equipes metiers",
			"equipes metier",
			"business teams",
			"parties prenantes",
			"stakeholder",
			"accompagnement",
			"accompagner",
			"accompagnerez",
			"adoption",
			"conduite du changement",
			"change management",
			"demonstration",
		],
	},
	{
		id: "research",
		label: { fr: "recherche et R&D", en: "research and R&D" },
		weight: 2,
		terms: [
			"r&d",
			"research",
			"publication",
			"etat de l'art",
			"state of the art",
			"recherche clinique",
			"recherche appliquee",
			"scientifique",
			"scientific",
		],
	},
	{
		id: "typescript",
		label: { fr: "TypeScript et web", en: "TypeScript and web" },
		weight: 1,
		terms: [
			"typescript",
			"javascript",
			"react",
			"node.js",
			"nodejs",
			"front-end",
			"frontend",
		],
	},
	{
		id: "coding-assistants",
		label: { fr: "assistants de code IA", en: "AI coding assistants" },
		weight: 1,
		terms: [
			"claude code",
			"copilot",
			"github copilot",
			"cursor",
			"assistants de code",
			"coding assistant",
		],
	},
	{
		id: "product",
		label: { fr: "démarche produit et MVP", en: "product mindset and MVP" },
		weight: 1,
		terms: [
			"mvp",
			"poc",
			"proof of concept",
			"prototype",
			"prototypage",
			"prototyping",
			"esprit produit",
			"product mindset",
			"cas d'usage",
			"use case",
			"agile",
			"scrum",
		],
	},
] as const satisfies readonly Competence[];

export type CompetenceId = (typeof competences)[number]["id"];

export const competenceIds = competences.map((c) => c.id) as [
	CompetenceId,
	...CompetenceId[],
];

export const competenceById: ReadonlyMap<string, Competence> = new Map(
	competences.map((c) => [c.id, c]),
);
